'use client';
import { useEffect } from 'react';
import { ArrowUpRight, ArrowDown, CodeXml as Github, Mail, MapPin } from 'lucide-react';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';

const projects = [
  { id: 'little-bolt', number: '01', name: 'Little Bolt, Big Moon', category: 'Browsergame', tags: ['JavaScript', 'Canvas', 'ES-Module'], description: 'Ein kleiner Roboter auf dem Weg zum Mond. Ein vertikaler Platformer mit aufladbaren Sprüngen, Gegnern und einer eigenen Spielwelt.', image: '/assets/little-bolt.png', alt: 'Titelbild von Little Bolt, Big Moon: ein Roboter unter einem großen Mond', caption: 'Original-Titelbild des Projekts', repo: 'https://github.com/willidevac/Little-Bolt-Big-Moon', details: 'Die Spielwelt wird mit HTML5 Canvas dargestellt. Native JavaScript-Module und Klassen strukturieren die Spiellogik; Einstellungen und lokale Rekorde werden im Browser gespeichert.', challenge: 'Das Zusammenspiel von Eingabe, Bewegung und Spielzustand muss über viele Situationen hinweg konsistent bleiben. Die dokumentierte Architektur trennt Zuständigkeiten und ergänzt sie um automatisierte Prüfungen.', status: 'Entwicklungsprojekt mit dokumentiertem Tutorial und Prüfsuite.' },
  { id: 'kochgoat', number: '02', name: 'KochGoat', category: 'Produktidee · in Entwicklung', tags: ['Nuxt / Vue', 'TypeScript', 'Symfony'], description: 'Eine Social-Cooking-Plattform als eigene Produktidee: Rezepte entdecken, Kochideen teilen und den Alltag rund ums Essen organisieren.', image: null, alt: '', caption: '', repo: null, details: 'Das Projekt enthält ein separates Nuxt-Frontend, ein Symfony-Backend mit API Platform sowie eine Marketing-Seite. Rezepte, Community und Einkaufslisten gehören zum vorgesehenen Produktumfang.', challenge: 'Aus einer umfangreichen Produktidee müssen klar abgegrenzte Funktionen und passende Schnittstellen entstehen. Die vorhandene Projektstruktur bildet Frontend, Backend und Außendarstellung getrennt ab.', status: 'In Entwicklung. Der vollständige Funktionsumfang ist noch nicht als fertiges Produkt ausgewiesen.' },
  { id: 'join', number: '03', name: 'JOIN', category: 'Webanwendung · Weiterbildung', tags: ['Task-Management', 'Webentwicklung'], description: 'Ein Projekt für die Organisation von Aufgaben. Im Mittelpunkt steht die übersichtliche Darstellung von Arbeit und Projektfortschritt.', image: null, alt: '', caption: '', repo: null, details: 'JOIN ist eine Projekt- und Task-Management-Anwendung aus meiner Weiterbildung. Eine ausführliche Dokumentation zu Funktionen und meiner Aufgabenverteilung folgt.', challenge: null, status: 'Weiterbildungsprojekt. Projektbeschreibung wird ergänzt.' },
  { id: 'pokedex', number: '04', name: 'Pokédex', category: 'API-Projekt', tags: ['JavaScript', 'REST-API', 'HTML / CSS'], description: 'Pokémon suchen und ihre Eigenschaften entdecken. Daten aus der PokéAPI werden geladen und in einer interaktiven Oberfläche dargestellt.', image: null, alt: '', caption: '', repo: 'https://github.com/willidevac/pokedex', details: 'Asynchrone API-Abfragen laden Listen und Detaildaten. Map-Caches halten bereits geladene Antworten bereit. Suchfunktion und Detailansichten erschließen den Datenbestand.', challenge: 'Viele Detailabfragen können unabhängig voneinander fehlschlagen. Promise.allSettled verarbeitet die Antworten getrennt; HTTP-Fehler werden geprüft und bereits geladene Daten wiederverwendet.', status: 'JavaScript-Projekt mit Such- und Detailfunktionen.' },
  { id: 'bestellapp', number: '05', name: 'Bestellapp', category: 'Interaktive Webanwendung', tags: ['JavaScript', 'HTML', 'CSS'], description: 'Gerichte auswählen, Mengen ändern und den Warenkorb verwalten. Eine Bestelloberfläche mit direkter Rückmeldung bei jeder Auswahl.', image: '/assets/ramen.jpg', alt: 'Ramen-Gericht aus den Bildmaterialien der Bestellapp', caption: 'Bildmaterial aus dem Projekt', repo: 'https://github.com/willidevac/bestellapp', details: 'Separate JavaScript-Dateien übernehmen Menüdarstellung, Warenkorbsteuerung und Rückmeldungen. Artikel lassen sich hinzufügen, reduzieren und entfernen; eine mobile Warenkorbansicht ist vorgesehen.', challenge: 'Mengenänderungen und Darstellung müssen zusammenpassen. Warenkorbsteuerung und Rendering sind im vorhandenen Code in eigene Bereiche aufgeteilt.', status: 'Frontend-Projekt mit Bestellfeedback; keine echte Bestell- oder Zahlungsabwicklung.' },
  { id: 'fotogram', number: '06', name: 'Fotogram', category: 'Bildergalerie', tags: ['JavaScript', 'HTML', 'CSS'], description: 'Eine Fotogalerie mit FoodGram-Gestaltung. Bilder lassen sich vergrößern und mit Maus oder Tastatur durchblättern.', image: '/assets/fotogram.jpg', alt: 'Sushi-Foto aus der FoodGram-Galerie', caption: 'Bildmaterial aus dem Projekt', repo: 'https://github.com/willidevac/fotogram-project', details: 'Die Galerie öffnet Bilder in einer Lightbox. Pfeiltasten wechseln zwischen den Bildern, Escape schließt die Ansicht. Die Navigation springt am Ende wieder zum Anfang.', challenge: 'Maus- und Tastaturbedienung greifen auf denselben Bildindex zu. Gemeinsame Funktionen aktualisieren die Ansicht unabhängig davon, wie navigiert wird.', status: 'Frontend-Projekt mit Galerie und Lightbox.' },
];

export default function Home() {
  useEffect(() => {
    type PortfolioTool = { name: string; title: string; description: string; inputSchema: object; annotations: { readOnlyHint: boolean }; execute: (input: unknown) => unknown };
    const context = (document as Document & { modelContext?: { registerTool: (tool: PortfolioTool, options: { signal: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!context?.registerTool) return;
    const lifecycle = new AbortController();
    try {
      void Promise.resolve(context.registerTool({
        name: 'list_portfolio_projects', title: 'Portfolio-Projekte lesen',
        description: 'Liest die sechs auf dieser Seite dargestellten Projekte mit Technologien und Entwicklungsstand.',
        inputSchema: { type: 'object', properties: {}, additionalProperties: false },
        annotations: { readOnlyHint: true },
        execute(input) {
          if (!input || typeof input !== 'object' || Array.isArray(input) || Object.keys(input).length) throw new Error('Ein leeres Objekt wird erwartet.');
          return projects.map(({ id, name, tags, description, status, repo }) => ({ id, name, tags, description, status, repo }));
        },
      }, { signal: lifecycle.signal })).catch(() => {});
    } catch { /* Optional browser capability. */ }
    return () => lifecycle.abort();
  }, []);
  return <>
    <a className="skip-link" href="#inhalt">Zum Inhalt</a>
    <header className="site-header wrap"><a className="brand" href="#start" aria-label="Jayanath Willi Kasberg – Startseite"><span className="brand-mark">jw<span>.</span></span><span>Jayanath Willi Kasberg</span></a><nav aria-label="Hauptnavigation"><a href="#projekte">Projekte</a><a href="#ueber-mich">Über mich</a><a className="nav-contact" href="#kontakt">Kontakt <ArrowUpRight size={16}/></a></nav></header>
    <main id="inhalt"><section id="start" className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> DUALES INFORMATIKSTUDIUM · 2027</p><h1>Technik verstehen.<br/>Software <span>entwickeln.</span></h1><p className="intro">Ich bin Jayanath Willi Kasberg. Auf meinem Weg in die Softwareentwicklung entstehen Webanwendungen, interaktive Oberflächen und ein Spiel mit einem ziemlich großen Mond.</p><div className="hero-actions"><a className="button primary" href="#projekte">Meine Projekte <ArrowDown size={18}/></a><a className="text-link" href="https://github.com/willidevac" target="_blank" rel="noreferrer"><Github size={18}/> GitHub <ArrowUpRight size={16}/></a></div><p className="location"><MapPin size={15}/> Berlin <span> / </span> Full-Stack-Weiterbildung</p></div><aside className="hero-aside"><div className="portrait-frame"><img src="/assets/portrait.jpg" alt="Jayanath Willi Kasberg" width="440" height="440"/><span className="portrait-label">Hallo, ich bin Willi.</span></div><div className="aside-caption"><span>MEIN NÄCHSTER SCHRITT</span><p>Theorie und Praxis<br/>im dualen Studium verbinden.</p></div></aside></section>
      <section id="projekte" className="projects-section wrap"><div className="section-heading"><div><p className="eyebrow">01 / AUSGEWÄHLTE ARBEITEN</p><h2>Ideen, die Code<br/>geworden sind.</h2></div><p>Sechs Projekte aus Weiterbildung<br/>und eigener Entwicklung.</p></div><div className="project-grid">{projects.map(project => <article className={`project-card project-${project.id}`} id={project.id} key={project.id}><div className={`project-visual ${!project.image ? 'type-visual' : ''}`}>{project.image ? <img src={project.image} alt={project.alt} loading="lazy" width="1000" height="560"/> : <><span className="visual-category">{project.category}</span><span className="project-wordmark">{project.name}<span>.</span></span><span className="visual-subline">{project.id === 'kochgoat' ? 'Kochen. Teilen. Entdecken.' : project.id === 'join' ? 'Aufgaben im Blick.' : 'Daten entdecken.'}</span></>}<span className="project-number">{project.number}</span></div><div className="project-body"><p className="project-category">{project.category}</p><h3>{project.name}</h3><p className="project-description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><Accordion><AccordionItem value={project.id}><AccordionTrigger className="project-trigger">Projekt im Detail</AccordionTrigger><AccordionContent className="project-details"><p>{project.details}</p>{project.challenge && <><h4>Technischer Einblick</h4><p>{project.challenge}</p></>}<h4>Projektstand</h4><p>{project.status}</p>{project.caption && <p className="image-note">Abbildung: {project.caption}.</p>}</AccordionContent></AccordionItem></Accordion>{project.repo && <a className="repo-link" href={project.repo} target="_blank" rel="noreferrer"><Github size={16}/> Code auf GitHub <ArrowUpRight size={16}/></a>}</div></article>)}</div></section>
      <section id="ueber-mich" className="about-section"><div className="wrap about-grid"><div><p className="eyebrow">02 / ÜBER MICH</p><h2>Ein technischer<br/>Weg. Ein neues<br/><span>Kapitel.</span></h2></div><div className="about-content"><p className="about-lead">Von der Kfz-Mechatronik zur Softwareentwicklung.</p><p>Meine technische Ausbildung und acht Jahre bei der Bundeswehr haben meinen bisherigen Weg geprägt. Heute qualifiziere ich mich parallel an der Bundeswehrfachschule Berlin und in der Full-Stack-Weiterbildung der Developer Akademie weiter.</p><p>Mein Ziel ist ein duales Informatikstudium ab 2027. In meinen Projekten beschäftige ich mich mit Benutzeroberflächen, Anwendungslogik und dem Zusammenspiel von Frontend und Backend.</p><div className="timeline"><div><span>SEIT 2026</span><p>Full-Stack-Weiterbildung<br/><small>Developer Akademie · voraussichtlich bis Mai 2027</small></p></div><div><span>2026</span><p>Fachhochschulreife angestrebt<br/><small>Bundeswehrfachschule Berlin · voraussichtlich Dezember 2026</small></p></div><div><span>2018–2026</span><p>Bundeswehr<br/><small>Technische und organisatorische Tätigkeiten</small></p></div><div><span>2017</span><p>Ausbildung zum Kfz-Mechatroniker abgeschlossen</p></div></div></div></div></section>
      <section className="skills-section wrap"><div><p className="eyebrow">03 / TECHNIK IM EINSATZ</p><h2>Werkzeuge mit<br/>Projektbezug.</h2></div><div className="skill-list"><div><h3>Frontend</h3><p>HTML · CSS · JavaScript</p><span>Oberflächen, Galerie, Warenkorb und API-Anbindung</span></div><div><h3>Spielentwicklung</h3><p>Canvas · ES-Module · Klassen</p><span>Spielwelt und strukturierte Logik in Little Bolt</span></div><div><h3>Full-Stack-Projekt</h3><p>Nuxt / Vue · TypeScript · Symfony</p><span>Frontend und Backend im Projekt KochGoat</span></div><div><h3>Entwicklungswerkzeuge</h3><p>Git · Visual Studio Code · Node.js</p><span>Versionsverwaltung und lokale Entwicklung</span></div></div></section>
      <section id="kontakt" className="contact-section"><div className="wrap contact-inner"><p className="eyebrow">04 / KONTAKT</p><h2>Über Projekte sprechen.<br/><span>Gemeinsam weiterdenken.</span></h2><p>Sie suchen einen motivierten Bewerber für ein duales<br className="desktop-break"/> Informatikstudium ab 2027? Ich freue mich auf den Austausch.</p><a className="button contact-button" href="mailto:j.willi.kasberg@gmail.com"><Mail size={20}/> Nachricht schreiben <ArrowUpRight size={18}/></a><a className="email-text" href="mailto:j.willi.kasberg@gmail.com">j.willi.kasberg@gmail.com</a></div></section>
    </main><footer className="wrap footer"><span>© 2026 Jayanath Willi Kasberg</span><span>IT-Portfolio · Berlin</span><a href="https://github.com/willidevac" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></footer>
  </>;
}
